improve configure

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -6,7 +6,7 @@
 PREFIX="/usr/local"
 MPIR_DIR="/usr/local"
 MPFR_DIR="/usr/local"
-FLINT_DIR="/home/fredrik/src/flint2/flint2"
+FLINT_DIR="/usr/local"
 SHARED=1
 STATIC=1
 
@@ -18,6 +18,7 @@ usage()
    echo "   where <args> may be:"
    echo "     --with-mpir=<path> Specify location of MPIR"
    echo "     --with-mpfr=<path> Specify location of MPFR"
+   echo "     --with-flint=<path> Specify location of FLINT"
    echo "     --prefix=<path>    Specify path to installation location"
    echo "     --disable-shared   Do not build a shared library"
    echo "     --disable-static   Do not build a static library"
@@ -36,6 +37,9 @@ until [ -z "$1" ]; do
          ;;
       "--with-mpfr="*)
          MPFR_DIR=`expr substr $1 13 length $1`
+         ;;
+      "--with-flint="*)
+         FLINT_DIR=`expr substr $1 14 length $1`
          ;;
       "--prefix="*)
          PREFIX=`expr substr $1 10 length $1`
@@ -84,8 +88,20 @@ else
    exit 1
 fi
 
-FLINT_LIB_DIR="${FLINT_DIR}"
-FLINT_INCLUDE_DIR="${FLINT_DIR}"
+if [ -d "${FLINT_DIR}/lib" ]; then
+   FLINT_LIB_DIR="${FLINT_DIR}/lib"
+   FLINT_INCLUDE_DIR="${FLINT_DIR}/include"
+elif [ -d "${FLINT_DIR}/.libs" ]; then
+   FLINT_LIB_DIR="${FLINT_DIR}/.libs"
+   FLINT_INCLUDE_DIR="${FLINT_DIR}"
+elif [ -e "${FLINT_DIR}/flint.h" ]; then
+   FLINT_LIB_DIR="/scratch/fjohanss/flint2"
+   FLINT_INCLUDE_DIR="/scratch/fjohanss/flint2"
+else
+   echo "${FLINT_DIR}"
+   echo "Invalid FLINT directory?"
+   exit 1
+fi
 
 if [ "`uname`" = "Linux" -a "`uname -m`" = "x86_64" ]; then
    ARB_TUNE="-funroll-loops "
